### ISSUE TITLE
Neurosynth Compose: Ecosystem for Reproducible Meta-Analyses

### ISSUE THREAD

**Issue by jdkent** [ohbm/hackathon2024#20]
### Title

Neurosynth Compose: Ecosystem for Reproducible Meta-Analyses

### Short description and the goals for the OHBM BrainHack

We are aiming to make meta-analyses more systematic, reproducible, and overall less painful with an online interface and lots of pre-ingested data for you to use freely!

Our platform now hosts over 30,000 neuroimaging papers that report coordinates, making the arduous phase of transcribing coordinates simpler than ever.

We have a number of projects to work on, whether it's your first time programming or if you're a seasoned veteran.

## Novice

- Test out our sleuth file import feature (try to break it and give feedback)
- Work on a script to add DOI/PMID to the sleuth files automatically
- Use our tutorial and give feedback
- Help validate paper-extracted information from GPT

## Intermediate

- write code to create figures to do some exploratory data analysis/Validation on data we've ingested.
- formalize the DOI/PMID adding script into a function in NiMARE
- profile memory consumption in running the NiMARE reports CBMA module
- add documentation to publang: interface to extract information from academic papers (https://github.com/adelavega/publang)

## Advanced

- redo the cognitive atlas python package using a more modern API generator
- help create a script to extract references to papers within meta-analysis papers
- create a [NIDM to NiMARE](https://github.com/neurostuff/NiMARE/issues/837) function
- Prompt Engineering/workflow design for publang to extract task information
- representing participant demographics in our database.

### Link to the Project

https://github.com/neurostuff/neurostore

### Image/Logo for the OHBM brainhack website

https://github.com/neurostuff/neurostore/blob/master/compose/neurosynth-frontend/public/static/synth.png

### Project lead

James Kent @jdkent jdkent
Alejandro De La Vega  @adelavega neurozorro
Julio Peraza @JulioAPeraza N/A

### Main Hub

Seoul

### Other hubs covered by the leaders

- [X] Seoul
- [ ] Hybrid (Asia / Pacific)
- [ ] Hybrid (Europe / Middle East / Africa)
- [X] Hybrid (Americas)

### Skills

- None
- Ran a meta-analysis before (using any technology)
- written a bash script
- read in files with python
- use plotting libraries with python
- created a pull request using git/github

### Twitter summary

If you're interested in or learning about meta-analyses, AI, data engineering, and everything in between, come checkout Neurosynth Compose! We have projects for every skill level.

### Short name for the Discord chat channel (~15 chars)

neurosynth-compose

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon

**Comment by bhvieira** [comment]
Project submissions for the OHBM BrainHack 2025 (June 21–23, Brisbane) are now open!
If you’d like to continue your 2024 project, start a new one, or just get involved early, submit here: [https://github.com/ohbm/hackathon2025/issues/](https://github.com/ohbm/hackathon2025/issues/new?assignees=bhvieira&labels=Hackathon+Project&projects=&template=brainhack-hacktrack-project.yml&title=%3CMy+Project+Name%3E
)  😊
